server:
  port: 3000
  logLevel: info

static:
  paths:
    assets: public/assets
    js: public/js
    css: public/css

i18n:
  languages: [ en-US, de-DE ]
  fallbackLng: en-US
  namespaces: [ generic, home ]
  fallbackNS: generic
  pattern: "locales/{{lng}}/{{ns}}.json"
  missing: "locales/{{lng}}/{{ns}}.missing.json"
  preload: [ en-US ]

rateLimit:
  windowMs: 900000
  limit: 1000

cookies:
  locale: en-US
  theme: light
  units: metric
