name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Build App
        run: npm run build

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v7
        with:
          name: build-dist
          path: dist/
          if-no-files-found: error
          compression-level: 9
